#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
# Set the prompt
autoload -Uz promptinit
promptinit
prompt kylewest

# Source my .profile
[[ -e ~/.profile ]] && emulate sh -c 'source ~/.profile'

# For support-firecloud
source '/Users/fred/git/firecloud/support-firecloud/sh/dev.inc.sh'
